### ISSUE TITLE
Seeking Advice: Assigning to 'arguments' in strict mode

### ISSUE THREAD

**Issue by nicoandmee** [jehna/humanify#251]
Hi there, I'm trying to use this project to deobsfucate/unpack the following [script](https://datadome.seatgeek.com/tags.js).
One thing I'm running into is the following error:
```
Processing file 1/2
/home/nico/code/github.com/nicoandmee/humanify/node_modules/.pnpm/@babel+parser@7.26.3/node_modules/@babel/parser/lib/index.js:359
    const error = new SyntaxError();
                  ^

SyntaxError: unknown: Assigning to 'arguments' in strict mode. (2951:23)

  2949 |                         g[y] = arguments[y];
  2950 |                       }
> 2951 |                       (arguments = g)[1] = {};
       |                        ^
  2952 |                     }
  2953 |                     arguments[1].credentials = "include";
  2954 |                   }
    at constructor (/home/nico/code/github.com/nicoandmee/humanify/node_modules/.pnpm/@babel+parser@7.26.3/node_modules/@babel/parser/lib/index.js:359:19)
    at Parser.raise (/home/nico/code/github.com/nicoandmee/humanify/node_modules/.pnpm/@babel+parser@7.26.3/node_modules/@babel/parser/lib/index.js:3266:19)
    at Parser.checkIdentifier (/home/nico/code/github.com/nicoandmee/humanify/node_modules/.pnpm/@babel+parser@7.26.3/node_modules/@babel/parser/lib/index.js:7340:14)
    at Parser.checkLVal (/home/nico/code/github.com/nicoandmee/humanify/node_modules/.pnpm/@babel+parser@7.26.3/node_modules/@babel/parser/lib/index.js:7294:12)
    at Parser.parseMaybeAssign (/home/nico/code/github.com/nicoandmee/humanify/node_modules/.pnpm/@babel+parser@7.26.3/node_modules/@babel/parser/lib/index.js:10410:12)
    at /home/nico/code/github.com/nicoandmee/humanify/node_modules/.pnpm/@babel+parser@7.26.3/node_modules/@babel/parser/lib/index.js:10353:39
    at Parser.allowInAnd (/home/nico/code/github.com/nicoandmee/humanify/node_modules/.pnpm/@babel+parser@7.26.3/node_modules/@babel/parser/lib/index.js:11955:12)
    at Parser.parseMaybeAssignAllowIn (/home/nico/code/github.com/nicoandmee/humanify/node_modules/.pnpm/@babel+parser@7.26.3/node_modules/@babel/parser/lib/index.js:10353:17)
    at Parser.parseParenAndDistinguishExpression (/home/nico/code/github.com/nicoandmee/humanify/node_modules/.pnpm/@babel+parser@7.26.3/node_modules/@babel/parser/lib/index.js:11214:28)
 ```
 
 I understand why babel is throwing here (error is quite clear), but any recommendations on the best way to deal with it? Thank u :pray:

**Comment by jehna** [comment]
Right, I'm guessing that using `arguments` is such a special case that it hasn't been brought up before. Sounds like a bug for me!

**Comment by jehna** [comment]
@nicoandmee can you check the version 2.2.2, it should have a fix for this issue
